sudo: required

services:
- docker

arch:
  packages:
  - lldb
  - llvm-libs
  - llvm
  - clang
  - ninja
  - cmake
  script:
  - "./ci/travis.sh"

script:
- "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
